import { Suspense, useEffect, useState } from 'react';
import { NavLink, Link, Outlet, useLocation, useNavigate } from 'react-router-dom';
import { House, Swords, Trophy, ChartNoAxesColumnIncreasing, UserRound, Moon, Sun, Bell, ChevronDown, Settings2, Layers3, ArrowUpRight, Coins } from 'lucide-react';
import { useApp } from '../context';
import { Avatar, Modal, Skeleton, League } from './ui';
import { useResource, number, type Row } from '../api';
import { tg, haptic } from '../telegram';
const nav=[{to:'/',label:'Главная',icon:House},{to:'/play',label:'Играть',icon:Swords},{to:'/tournaments',label:'Турниры',icon:Trophy},{to:'/leaderboard',label:'Рейтинг',icon:ChartNoAxesColumnIncreasing},{to:'/profile',label:'Профиль',icon:UserRound}];
export default function Layout(){
 const {me,mock,switchUser,toast,version}=useApp();const [demo,setDemo]=useState(false);
 const [theme,setTheme]=useState(localStorage.getItem('pt-theme')||'light');
 const users=useResource<Row[]>(mock?'/auth/demo-users':'/players?search=');
 const notifications=useResource<Row[]>('/me/notifications',version);const location=useLocation(),navigate=useNavigate();
 useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem('pt-theme',theme);try{tg()?.setHeaderColor?.(theme==='dark'?'#183b36':'#fffde9');tg()?.setBackgroundColor?.(theme==='dark'?'#183b36':'#fffde9');}catch{}},[theme]);
 useEffect(()=>{window.scrollTo(0,0);const app=tg();if(!app?.initData)return;const back=()=>navigate(-1);if(location.pathname!=='/')app.BackButton.show();else app.BackButton.hide();app.BackButton.onClick(back);
 const viewport=()=>{const s=document.documentElement.style;s.setProperty('--tg-viewport',`${app.viewportStableHeight||window.innerHeight}px`);s.setProperty('--tg-safe-top',`${(app.safeAreaInset?.top||0)+(app.contentSafeAreaInset?.top||0)}px`);s.setProperty('--tg-safe-bottom',`${app.safeAreaInset?.bottom||0}px`);};
 app.onEvent('viewportChanged',viewport);app.onEvent('safeAreaChanged',viewport);app.onEvent('contentSafeAreaChanged',viewport);viewport();return()=>{app.BackButton.offClick(back);app.offEvent('viewportChanged',viewport);app.offEvent('safeAreaChanged',viewport);app.offEvent('contentSafeAreaChanged',viewport);};},[location.pathname,navigate]);
 return <div className="app-shell" onClickCapture={e=>{const el=(e.target as HTMLElement).closest('a,button,summary');if(el&&!el.hasAttribute('disabled'))haptic(el.closest('.tabs,.bottom-nav,.sidebar')?'selection':'soft');}}>
 <aside className="sidebar"><Link to="/" className="wordmark" aria-label="пинг таблет — главная">пинг таблет<span>●</span></Link><span className="brand-caption">встречаемся у стола</span><div className="nav-caption">твоя игра</div><nav>{nav.map(({to,label,icon:Icon})=><NavLink key={to} to={to} end={to==='/'}><Icon size={21}/><span>{label}</span></NavLink>)}</nav><div className="nav-caption">ещё немного магии</div><nav><NavLink to="/collection"><Layers3 size={21}/>Коллекция</NavLink><NavLink to="/shop"><Coins size={21}/>Магазин стикеров</NavLink>{me.role==='ADMIN'&&<NavLink to="/admin"><Settings2 size={21}/>Управление</NavLink>}</nav><div className="sidebar-bottom"><div className="season-mini"><span className="live-dot"/> сезон 01<p>Твоя подача.</p><Link to="/leaderboard">Выше в рейтинге <ArrowUpRight size={16}/></Link></div><Link className="account-row" to="/profile"><Avatar user={me}/><span><strong>{me.display_name.split(' ')[0]}</strong><League value={me.league}/></span></Link></div></aside>
 <div className="main-shell"><header className="topbar"><Link to="/" className="wordmark mobile-logo">пинг таблет<span>●</span></Link><span className="desktop-topline">маленький мяч. большая история.</span><div className="top-actions">{mock&&<button className="demo-button" onClick={()=>setDemo(true)}>Демо <ChevronDown size={12}/></button>}<Link to="/wallet" className="balance-pill" aria-label="Баланс пингпоинтов"><Coins size={17}/>{number(me.pingpoints)}<span> ПП</span></Link><button className="icon-btn theme-btn" aria-label={theme==='dark'?'Светлая тема':'Тёмная тема'} onClick={()=>setTheme(theme==='dark'?'light':'dark')}>{theme==='dark'?<Sun size={19}/>:<Moon size={19}/>}</button><Link to="/notifications" className="icon-btn notification-btn" aria-label="Уведомления"><Bell size={20}/>{notifications.data?.some(n=>!n.read_at)&&<i/>}</Link></div></header><main key={me.id}><div className="page-enter" key={location.pathname}><Suspense fallback={<Skeleton/>}><Outlet/></Suspense></div></main><footer className="desktop-footer"><span>пинг таблет © 2026</span><span>играем. знакомимся. собираем.</span></footer></div>
 <nav className="bottom-nav" aria-label="Основная навигация">{nav.map(({to,label,icon:Icon})=><NavLink key={to} to={to} end={to==='/'}><Icon size={22}/><span>{label}</span></NavLink>)}</nav>
 {demo&&<Modal title="Выбрать демо-игрока" onClose={()=>setDemo(false)}><p className="muted">Переключайтесь между игроками, чтобы проверить подтверждение матча. У Сэма есть права администратора.</p><div className="demo-users">{users.data?.map(u=><button className={`demo-user ${me.id===u.id?'selected':''}`} key={u.id} onClick={()=>switchUser(u.id).then(()=>{setDemo(false);navigate('/');}).catch(e=>toast(e.message))}><strong>{u.display_name}</strong><span>{u.role==='ADMIN'?'Администратор':u.role==='ORGANIZER'?'Организатор':'Игрок'}</span></button>)}</div></Modal>}</div>;
}
