import { useEffect, useState } from 'react';
import { NavLink, Link, Outlet, useLocation, useNavigate } from 'react-router-dom';
import { House, Swords, Trophy, ChartNoAxesColumnIncreasing, UserRound, Moon, Sun, Bell, ChevronDown, Settings2, Layers3, ArrowUpRight, Coins } from 'lucide-react';
import { useApp } from '../context';
import { Avatar, Modal } from './ui';
import { useResource, number, type Row } from '../api';
import { tg } from '../telegram';
const nav=[{to:'/',label:'Home',icon:House},{to:'/play',label:'Play',icon:Swords},{to:'/tournaments',label:'Tournaments',icon:Trophy},{to:'/leaderboard',label:'Leaderboard',icon:ChartNoAxesColumnIncreasing},{to:'/profile',label:'Profile',icon:UserRound}];
export default function Layout(){const {me,mock,switchUser,toast,version}=useApp();const [demo,setDemo]=useState(false);const [theme,setTheme]=useState(localStorage.getItem('ping-theme')||tg()?.colorScheme||'dark');const users=useResource<Row[]>('/auth/demo-users');const notifications=useResource<Row[]>('/me/notifications',version);const location=useLocation(),navigate=useNavigate();
 useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem('ping-theme',theme);},[theme]);
 useEffect(()=>{const app=tg();if(!app?.initData)return;const back=()=>navigate(-1);if(location.pathname!=='/')app.BackButton.show();else app.BackButton.hide();app.BackButton.onClick(back);const viewport=()=>document.documentElement.style.setProperty('--tg-viewport',`${app.viewportStableHeight||window.innerHeight}px`);const themeChanged=()=>setTheme(app.colorScheme);app.onEvent('viewportChanged',viewport);app.onEvent('themeChanged',themeChanged);viewport();return()=>{app.BackButton.offClick(back);app.offEvent('viewportChanged',viewport);app.offEvent('themeChanged',themeChanged);};},[location.pathname,navigate]);
 return <div className="app-shell"><aside className="sidebar"><Link to="/" className="wordmark" aria-label="PING home">PING<span>●</span></Link><span className="brand-caption">PLAY. WIN. COLLECT.</span><div className="nav-caption">YOUR GAME</div><nav>{nav.map(({to,label,icon:Icon})=><NavLink key={to} to={to} end={to==='/'}><Icon size={21}/><span>{label}</span></NavLink>)}</nav><div className="nav-caption">EXTRA SPIN</div><nav><NavLink to="/collection"><Layers3 size={21}/>Collection</NavLink><NavLink to="/shop"><Coins size={21}/>Sticker shop</NavLink>{me.role==='ADMIN'&&<NavLink to="/admin"><Settings2 size={21}/>Admin</NavLink>}</nav><div className="sidebar-bottom"><div className="season-mini"><span className="live-dot"/> SEASON 01<p>Make your mark.</p><Link to="/leaderboard">Climb the ranks <ArrowUpRight size={16}/></Link></div><Link className="account-row" to="/profile"><Avatar user={me}/><span><strong>{me.display_name.split(' ')[0]}</strong><small>{me.league} LEAGUE</small></span><ArrowUpRight size={17}/></Link></div></aside>
 <div className="main-shell"><header className="topbar"><Link to="/" className="wordmark mobile-logo">PING<span>●</span></Link><span className="desktop-topline">THE CLUBHOUSE <span>/</span> YOUR NEXT LEVEL STARTS HERE</span><div className="top-actions">{mock&&<button className="demo-button" onClick={()=>setDemo(true)}>DEMO <ChevronDown size={12}/></button>}<Link to="/wallet" className="balance-pill"><Coins size={17}/>{number(me.pingpoints)}<span> PP</span></Link><button className="icon-btn theme-btn" aria-label={`Switch to ${theme==='dark'?'light':'dark'} theme`} onClick={()=>setTheme(theme==='dark'?'light':'dark')}>{theme==='dark'?<Sun size={19}/>:<Moon size={19}/>}</button><Link to="/notifications" className="icon-btn notification-btn" aria-label="Notifications"><Bell size={20}/>{notifications.data?.some(n=>!n.read_at)&&<i/>}</Link></div></header><main key={me.id}><Outlet/></main><footer className="desktop-footer"><span>PING CLUB © 2026</span><span>A little competition. A lot of good times.</span><span>PLAY. WIN. COLLECT.</span></footer></div><nav className="bottom-nav">{nav.map(({to,label,icon:Icon})=><NavLink key={to} to={to} end={to==='/'}><Icon size={21}/><span>{label}</span></NavLink>)}</nav>
 {demo&&<Modal title="Choose a demo player" onClose={()=>setDemo(false)}><p className="muted">Try an opponent’s confirmation, or use Sam River to explore admin controls.</p><div className="demo-users">{users.data?.map(u=><button className={`demo-user ${me.id===u.id?'selected':''}`} key={u.id} onClick={()=>switchUser(u.id).then(()=>{setDemo(false);navigate('/');}).catch(e=>toast(e.message))}><strong>{u.display_name}</strong><span>{u.role}</span></button>)}</div></Modal>}</div>;
}
