import { useRef, useEffect, type ReactNode } from 'react';
import { Link } from 'react-router-dom';
import { ArrowUpRight, X, ArrowRight, Trophy, LockKeyhole } from 'lucide-react';
import { type Row, number } from '../api';
export function Avatar({user,size='normal'}:{user:Row;size?:string}){return <span className={`avatar ${size}`} style={{'--avatar-hue':`${Number(user.avatar||0)*39}deg`} as React.CSSProperties}>{user.profile_photo?<img src={user.profile_photo} alt="" onError={e=>{e.currentTarget.style.display='none';}}/>:<span>{(user.display_name||'P').split(' ').slice(0,2).map((v:string)=>v[0]).join('')}</span>}</span>;}
export function Skeleton(){return <div className="skeletons" aria-label="Loading" role="status"><div/><div/><div/></div>;}
export function ErrorView({message,retry}:{message:string;retry:()=>void}){return <div className="empty" role="alert"><h3>Let’s try that again.</h3><p>{message}</p><button className="btn" onClick={retry}>Try again <ArrowRight size={16}/></button></div>;}
export function Empty({title,text,action}:{title:string;text?:string;action?:ReactNode}){return <div className="empty"><Trophy size={32}/><h3>{title}</h3>{text&&<p>{text}</p>}{action}</div>;}
export function PageTitle({eyebrow,title,description,action}:{eyebrow?:string;title:string;description?:string;action?:ReactNode}){return <div className="page-title"><div>{eyebrow&&<span className="eyebrow">{eyebrow}</span>}<h1>{title}</h1>{description&&<p>{description}</p>}</div>{action}</div>;}
export function SectionTitle({title,to,label='View all'}:{title:string;to?:string;label?:string}){return <div className="section-title"><h2>{title}</h2>{to&&<Link to={to}>{label} <ArrowUpRight size={16}/></Link>}</div>;}
export function League({value}:{value:string}){return <span className={`league league-${value.toLowerCase()}`}><span>◆</span> {value}</span>;}
export function Modal({title,children,onClose}:{title:string;children:ReactNode;onClose:()=>void}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{ref.current?.showModal();return()=>ref.current?.close();},[]);return <dialog ref={ref} className="modal" onCancel={e=>{e.preventDefault();onClose();}} onClick={e=>{if(e.target===ref.current)onClose();}}><div className="modal-head"><h2>{title}</h2><button className="icon-btn" aria-label="Close dialog" onClick={onClose}><X/></button></div>{children}</dialog>;}
export function StickerCard({sticker,onClick}:{sticker:Row;onClick?:()=>void}){const locked=sticker.quantity===0;const inside=<><div className="sticker-art"><img src={sticker.image_url} alt={locked?'Locked sticker':sticker.name}/>{locked?<LockKeyhole className="sticker-lock" size={22}/>:sticker.quantity>1&&<span className="quantity">×{sticker.quantity}</span>}</div><span className="rarity">{sticker.rarity}</span><strong>{sticker.name}</strong></>;return onClick?<button className={`sticker-card rarity-${sticker.rarity.toLowerCase()} ${locked?'locked':''}`} onClick={onClick}>{inside}</button>:<div className={`sticker-card rarity-${sticker.rarity.toLowerCase()} ${locked?'locked':''}`}>{inside}</div>;}
export function Stat({label,value,note}:{label:string;value:string|number;note?:string}){return <div className="stat"><span>{label}</span><strong>{typeof value==='number'?number(value):value}</strong>{note&&<small>{note}</small>}</div>;}
export function FormError({message}:{message:string}){return message?<p className="form-error" role="alert">{message}</p>:null;}
