import type { FastifyInstance } from 'fastify';
import { z } from 'zod';
import { Store, now, id, audit, fail, requireRow } from '../db.js';
import { authorize, current } from '../auth.js';
import { credit, config, rarities } from '../domain/economy.js';
import { entityId, pathId, keySchema } from './player-routes.js';
export function adminRoutes(app:FastifyInstance,db:Store){
 app.addHook('preHandler',async req=>{if(req.url.startsWith('/api/admin'))authorize(db,req,['ADMIN']);});
 app.get('/api/admin/overview',async()=>({users:db.all('SELECT u.*,p.display_name,r.rating FROM users u JOIN profiles p ON p.user_id=u.id JOIN ratings r ON r.user_id=u.id ORDER BY p.display_name'),matches:db.all('SELECT * FROM matches ORDER BY created_at DESC LIMIT 100'),transactions:db.all('SELECT * FROM pingpoint_transactions ORDER BY created_at DESC LIMIT 100'),logs:db.all('SELECT * FROM admin_logs ORDER BY created_at DESC LIMIT 100'),config:config(db),packs:db.all('SELECT * FROM packs'),stickers:db.all('SELECT * FROM stickers'),achievements:db.all('SELECT * FROM achievements'),seasons:db.all('SELECT * FROM seasons')}));
 app.patch('/api/admin/users/:id',async req=>db.tx(()=>{const uid=pathId(req.params);const p=z.object({role:z.enum(['PLAYER','ORGANIZER','ADMIN']),banned:z.boolean()}).strict().parse(req.body);requireRow(db.get('SELECT id FROM users WHERE id=?',uid));if(uid===current(req)&&(p.role!=='ADMIN'||p.banned))fail('Keep your own admin account active');db.run('UPDATE users SET role=?,banned=? WHERE id=?',p.role,p.banned?1:0,uid);audit(db,current(req),'USER_UPDATE',uid,p);return {ok:true};}));
 app.post('/api/admin/adjustments',async req=>db.tx(()=>{const p=z.object({user_id:entityId,amount:z.number().int().min(-100000).max(100000).refine(n=>n!==0),description:z.string().trim().min(5).max(200),request_key:keySchema}).strict().parse(req.body);requireRow(db.get('SELECT id FROM users WHERE id=?',p.user_id));const added=credit(db,p.user_id,p.amount,'ADMIN_ADJUSTMENT',`${current(req)}:${p.request_key}`,p.description);if(added)audit(db,current(req),'PP_ADJUSTMENT',p.user_id,p);return {ok:true};}));
 app.patch('/api/admin/config',async req=>db.tx(()=>{const n=z.number().int().min(0).max(10000);const p=z.object({newK:n,regularK:n,highK:n,newGames:n,highRating:n,matchWin:n,matchLoss:n,tournamentParticipation:n,tournamentWin:n,dailyActivity:n,pairCooldownMinutes:n,dailyRewardMatches:n,leagues:z.array(z.object({name:z.string().min(2).max(20),min:n}).strict()).length(6)}).strict().parse(req.body);if(p.leagues.some((l,i)=>i===0?l.min!==0:l.min<=p.leagues[i-1].min))fail('League thresholds must start at 0 and increase');db.run('INSERT INTO config VALUES (?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value','game',JSON.stringify(p));audit(db,current(req),'CONFIG_UPDATE','game',p);return p;}));
 app.put('/api/admin/packs/:id',async req=>db.tx(()=>{const pid=pathId(req.params);const p=z.object({name:z.string().min(2).max(60),price:z.number().int().min(1).max(100000),active:z.boolean(),probabilities:z.record(z.enum(rarities),z.number().min(0).max(100))}).strict().parse(req.body);if(Math.abs(Object.values(p.probabilities).reduce((a,b)=>a+b,0)-100)>0.001)fail('Probabilities must add up to 100');for(const [rarity,weight] of Object.entries(p.probabilities))if(weight>0&&!db.get("SELECT id FROM stickers WHERE rarity=? AND type='COLLECTION'",rarity))fail('Add a collectible sticker for each enabled rarity first');db.run('INSERT INTO packs VALUES (?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,price=excluded.price,probabilities=excluded.probabilities,active=excluded.active',pid,p.name,p.price,JSON.stringify(p.probabilities),p.active?1:0);audit(db,current(req),'PACK_UPSERT',pid,p);return {ok:true};}));
 app.put('/api/admin/stickers/:id',async req=>db.tx(()=>{const sid=pathId(req.params);const p=z.object({name:z.string().min(2).max(80),description:z.string().max(300),image_url:z.string().max(1000).refine(v=>/^https:\/\//.test(v)||/^\/stickers\/[\w-]+\.svg$/.test(v)),rarity:z.enum(rarities)}).strict().parse(req.body);db.run("INSERT INTO stickers(id,name,description,image_url,rarity,season,type,created_at) VALUES (?,?,?,?,?,?,'COLLECTION',?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,description=excluded.description,image_url=excluded.image_url,rarity=excluded.rarity",sid,p.name,p.description,p.image_url,p.rarity,db.get("SELECT id FROM seasons WHERE status='CURRENT'")?.id||null,now());audit(db,current(req),'STICKER_UPSERT',sid,p);return {ok:true};}));
 app.post('/api/admin/achievements',async req=>db.tx(()=>{const p=z.object({name:z.string().min(2).max(80),description:z.string().max(300),metric:z.enum(['games','wins','longest_streak','tournament_wins','giant_slayer','collection','balance']),threshold:z.number().int().min(1).max(1000000),reward:z.number().int().min(0).max(10000)}).strict().parse(req.body);const aid=id();db.run('INSERT INTO achievements VALUES (?,?,?,?,?,?)',aid,p.name,p.description,p.metric,p.threshold,p.reward);audit(db,current(req),'ACHIEVEMENT_CREATE',aid,p);return {id:aid};}));
 app.post('/api/admin/seasons',async req=>db.tx(()=>{const p=z.object({name:z.string().min(2).max(80),start_at:z.string().datetime(),end_at:z.string().datetime(),status:z.enum(['UPCOMING','CURRENT','FINISHED'])}).strict().parse(req.body);if(p.end_at<=p.start_at)fail('Season end must follow its start');if(p.status==='CURRENT')db.run("UPDATE seasons SET status='FINISHED' WHERE status='CURRENT'");const sid=id();db.run('INSERT INTO seasons VALUES (?,?,?,?,?)',sid,p.name,p.start_at,p.end_at,p.status);audit(db,current(req),'SEASON_CREATE',sid,p);return {id:sid};}));
}
