import type { FastifyInstance } from 'fastify';
import { z } from 'zod';
import { Store, now, fail } from '../db.js';
import { current } from '../auth.js';
import { player, playerSelect } from '../domain/players.js';
import { balance, achievements, credit, config, openPack } from '../domain/economy.js';
import { league } from '../domain/rating.js';
import { confirmMatch, submitMatch } from '../domain/matches.js';
export const entityId=z.string().min(1).max(100).regex(/^[a-zA-Z0-9_-]+$/);
export const keySchema=z.string().min(8).max(100);
const pagination=z.object({limit:z.coerce.number().int().min(1).max(100).default(50),offset:z.coerce.number().int().min(0).max(100000).default(0)});
export const pathId=(p:unknown)=>z.object({id:entityId}).parse(p).id;
export const scoreSchema=z.object({score_a:z.number().int().min(0).max(99),score_b:z.number().int().min(0).max(99)});
export const matchList=(db:Store,user:string,limit=50,offset=0)=>db.all(`SELECT m.*,pa.display_name name_a,pb.display_name name_b FROM matches m JOIN profiles pa ON pa.user_id=m.player_a JOIN profiles pb ON pb.user_id=m.player_b WHERE (player_a=? OR player_b=?) ORDER BY created_at DESC LIMIT ? OFFSET ?`,user,user,limit,offset);
export function playerRoutes(app:FastifyInstance,db:Store){
  app.get('/api/me',async req=>player(db,current(req),true));
  app.patch('/api/me/profile',async req=>{
    const photo=z.string().max(750000).refine(v=>v===''||/^https:\/\//.test(v)||/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(v),'Use an HTTPS image or a PNG/JPEG/WebP photo');
    const p=z.object({display_name:z.string().trim().min(1).max(50),city:z.string().trim().max(80),bio:z.string().trim().max(300),profile_photo:photo.optional()}).strict().parse(req.body);
    db.run('UPDATE profiles SET display_name=?,city=?,bio=?,profile_photo=COALESCE(?,profile_photo),updated_at=? WHERE user_id=?',p.display_name,p.city,p.bio,p.profile_photo??null,now(),current(req));return player(db,current(req),true);
  });
  app.get('/api/players',async req=>{const q=pagination.extend({search:z.string().max(100).default('')}).parse(req.query);return db.all(`${playerSelect} WHERE u.banned=0 AND (p.display_name LIKE ? OR u.username LIKE ?) ORDER BY r.rating DESC LIMIT ? OFFSET ?`,`%${q.search}%`,`%${q.search}%`,q.limit,q.offset).map(p=>({...p,league:league(p.rating,config(db))}));});
  app.get('/api/players/:id',async req=>{const uid=pathId(req.params);const other=player(db,uid);const matches=db.all("SELECT m.*,pa.display_name name_a,pb.display_name name_b FROM matches m JOIN profiles pa ON pa.user_id=m.player_a JOIN profiles pb ON pb.user_id=m.player_b WHERE status='CONFIRMED' AND ((player_a=? AND player_b=?) OR (player_a=? AND player_b=?)) ORDER BY confirmed_at DESC",current(req),uid,uid,current(req));return {...other,head_to_head:{games:matches.length,wins:matches.filter(m=>m.winner===current(req)).length,losses:matches.filter(m=>m.loser===current(req)).length,matches:matches.slice(0,10)}};});
  app.get('/api/leaderboard',async req=>{const q=pagination.extend({metric:z.enum(['rating','streak','collectors']).default('rating')}).parse(req.query);const order={rating:'rating',streak:'streak',collectors:'collection'}[q.metric];return db.all(`SELECT u.id,p.display_name,p.avatar,p.profile_photo,p.city,r.rating,r.streak,(SELECT COUNT(*) FROM user_stickers us JOIN stickers s ON s.id=us.sticker_id WHERE us.user_id=u.id AND us.quantity>0 AND s.type='COLLECTION') collection FROM users u JOIN profiles p ON p.user_id=u.id JOIN ratings r ON r.user_id=u.id WHERE u.banned=0 ORDER BY ${order} DESC,r.rating DESC,u.id LIMIT ? OFFSET ?`,q.limit,q.offset).map((p,i)=>({...p,rank:q.offset+i+1,league:league(p.rating,config(db))}));});
  app.get('/api/players/:id/statistics',async req=>{const uid=pathId(req.params);return {player:player(db,uid),history:db.all('SELECT rating,created_at FROM rating_history WHERE user_id=? ORDER BY created_at',uid),best_win:db.get('SELECT p.display_name,r.rating FROM matches m JOIN profiles p ON p.user_id=m.loser JOIN ratings r ON r.user_id=m.loser WHERE m.winner=? ORDER BY r.rating DESC LIMIT 1',uid)||null};});
  app.get('/api/matches',async req=>{const q=pagination.parse(req.query);return matchList(db,current(req),q.limit,q.offset);});
  app.post('/api/matches',async req=>{const p=scoreSchema.extend({opponent_id:entityId,request_key:keySchema}).strict().parse(req.body);return submitMatch(db,current(req),p.opponent_id,p.score_a,p.score_b,p.request_key);});
  app.post('/api/matches/:id/confirm',async req=>confirmMatch(db,current(req),pathId(req.params)));
  app.post('/api/matches/:id/reject',async req=>{const mid=pathId(req.params);const result=db.run("UPDATE matches SET status='REJECTED' WHERE id=? AND player_b=? AND status='PENDING' AND tournament_id IS NULL",mid,current(req));if(!result.changes)fail('This match cannot be rejected',409);return {ok:true};});
  app.post('/api/matches/:id/cancel',async req=>{const result=db.run("UPDATE matches SET status='CANCELLED' WHERE id=? AND player_a=? AND status='PENDING' AND tournament_id IS NULL",pathId(req.params),current(req));if(!result.changes)fail('This match cannot be cancelled',409);return {ok:true};});
  app.get('/api/stickers',async()=>db.all("SELECT * FROM stickers WHERE type='COLLECTION' ORDER BY id"));
  app.get('/api/me/stickers',async req=>db.all('SELECT s.*,COALESCE(us.quantity,0) quantity FROM stickers s LEFT JOIN user_stickers us ON us.sticker_id=s.id AND us.user_id=? ORDER BY s.type,s.id',current(req)));
  app.get('/api/packs',async()=>db.all('SELECT * FROM packs WHERE active=1 ORDER BY price').map(p=>({...p,probabilities:JSON.parse(p.probabilities)})));
  app.post('/api/packs/:id/open',async req=>{const p=z.object({request_key:keySchema}).strict().parse(req.body);return openPack(db,current(req),pathId(req.params),p.request_key);});
  app.get('/api/me/pingpoints',async req=>{const q=pagination.parse(req.query);return {balance:balance(db,current(req)),transactions:db.all('SELECT * FROM pingpoint_transactions WHERE user_id=? ORDER BY created_at DESC LIMIT ? OFFSET ?',current(req),q.limit,q.offset)};});
  app.post('/api/me/daily',async req=>db.tx(()=>{const added=credit(db,current(req),config(db).dailyActivity,'BONUS',`daily:${now().slice(0,10)}`,'Daily warm-up');achievements(db,current(req));return {claimed:added,balance:balance(db,current(req))};}));
  app.get('/api/me/achievements',async req=>db.all('SELECT a.*,ua.created_at unlocked_at FROM achievements a LEFT JOIN user_achievements ua ON ua.achievement_id=a.id AND ua.user_id=? ORDER BY ua.created_at DESC,a.threshold',current(req)));
  app.get('/api/me/notifications',async req=>db.all('SELECT * FROM notifications WHERE user_id=? ORDER BY created_at DESC LIMIT 50',current(req)));
  app.post('/api/me/notifications/read',async req=>{db.run('UPDATE notifications SET read_at=? WHERE user_id=? AND read_at IS NULL',now(),current(req));return {ok:true};});
  app.get('/api/seasons/current',async()=>db.get("SELECT * FROM seasons WHERE status='CURRENT'")||null);
}
