import type { FastifyInstance } from 'fastify';
import { z } from 'zod';
import QRCode from 'qrcode';
import { Store, id, now, fail, requireRow, audit } from '../db.js';
import { current, authorize } from '../auth.js';
import { entityId, pathId, scoreSchema } from './player-routes.js';
import { joinTournament, startTournament, tournamentResult, organizer, qrToken } from '../domain/tournaments.js';
export const tournamentSchema=z.object({title:z.string().trim().min(3).max(100),description:z.string().max(1000).default(''),location:z.string().trim().min(2).max(160),start_at:z.string().datetime(),registration_deadline:z.string().datetime(),max_players:z.number().int().min(2).max(64),format:z.literal('SINGLE_ELIMINATION').default('SINGLE_ELIMINATION')}).strict();
export function createTournament(db:Store,user:string,p:z.infer<typeof tournamentSchema>){if(p.registration_deadline>p.start_at||p.registration_deadline<now())fail('Регистрация должна завершиться до начала турнира и быть в будущем');const tid=id();db.run("INSERT INTO tournaments(id,title,description,organizer_id,location,start_at,registration_deadline,max_players,format,status,qr_token,season_id,created_at) VALUES (?,?,?,?,?,?,?,?,?,'OPEN',?,?,?)",tid,p.title,p.description,user,p.location,p.start_at,p.registration_deadline,p.max_players,p.format,qrToken(),db.get("SELECT id FROM seasons WHERE status='CURRENT'")?.id||null,now());audit(db,user,'TOURNAMENT_CREATE',tid,p);return {id:tid};}
function detail(db:Store,tid:string,user:string){const t=requireRow(db.get('SELECT t.*,p.display_name organizer_name FROM tournaments t JOIN profiles p ON p.user_id=t.organizer_id WHERE t.id=?',tid));const manage=t.organizer_id===user||db.get('SELECT role FROM users WHERE id=?',user)?.role==='ADMIN';const {qr_token,...safe}=t;return {...safe,can_manage:manage,players:db.all('SELECT u.id,p.display_name,p.profile_photo,p.avatar,r.rating FROM tournament_players tp JOIN users u ON u.id=tp.user_id JOIN profiles p ON p.user_id=u.id JOIN ratings r ON r.user_id=u.id WHERE tournament_id=? ORDER BY rating DESC',tid),bracket:db.all('SELECT tm.*,pa.display_name name_a,pb.display_name name_b,pw.display_name winner_name FROM tournament_matches tm LEFT JOIN profiles pa ON pa.user_id=tm.player_a LEFT JOIN profiles pb ON pb.user_id=tm.player_b LEFT JOIN profiles pw ON pw.user_id=tm.winner WHERE tournament_id=? ORDER BY round,position',tid)};}
export function tournamentRoutes(app:FastifyInstance,db:Store){
 app.get('/api/tournaments',async()=>db.all('SELECT t.id,t.title,t.description,t.location,t.start_at,t.registration_deadline,t.max_players,t.format,t.status,t.organizer_id,t.champion_id,(SELECT COUNT(*) FROM tournament_players WHERE tournament_id=t.id) player_count FROM tournaments t ORDER BY t.start_at'));
 app.post('/api/tournaments',async req=>{authorize(db,req,['ORGANIZER','ADMIN']);return db.tx(()=>createTournament(db,current(req),tournamentSchema.parse(req.body)));});
 app.get('/api/tournaments/:id',async req=>detail(db,pathId(req.params),current(req)));
 app.get('/api/tournaments/:id/bracket',async req=>detail(db,pathId(req.params),current(req)).bracket);
 app.post('/api/tournaments/:id/join',async req=>{const p=z.object({token:z.string().min(20).max(100).optional()}).strict().parse(req.body||{});return joinTournament(db,current(req),pathId(req.params),p.token);});
 app.get('/api/invitations/:token',async req=>{const {token}=z.object({token:z.string().min(20).max(100)}).parse(req.params);const t=requireRow(db.get('SELECT id FROM tournaments WHERE qr_token=?',token),'This invitation has expired');return detail(db,t.id,current(req));});
 app.get('/api/tournaments/:id/qr',async req=>{const t=requireRow(db.get('SELECT * FROM tournaments WHERE id=?',pathId(req.params)));organizer(db,current(req),t);const url=`${(process.env.WEB_URL||'http://127.0.0.1:5173').replace(/\/$/,'')}/join/${t.qr_token}`;return {url,token:t.qr_token,image:await QRCode.toDataURL(url,{width:320,margin:2})};});
 app.post('/api/tournaments/:id/qr/regenerate',async req=>db.tx(()=>{const t=requireRow(db.get('SELECT * FROM tournaments WHERE id=?',pathId(req.params)));organizer(db,current(req),t);db.run('UPDATE tournaments SET qr_token=? WHERE id=?',qrToken(),t.id);audit(db,current(req),'QR_REGENERATE',t.id,{});return {ok:true};}));
 app.post('/api/tournaments/:id/start',async req=>startTournament(db,current(req),pathId(req.params)));
 app.post('/api/tournaments/:id/matches/:matchId/result',async req=>{const p=z.object({id:entityId,matchId:entityId}).parse(req.params),s=scoreSchema.strict().parse(req.body);return tournamentResult(db,current(req),p.id,p.matchId,s.score_a,s.score_b);});
 app.post('/api/tournaments/:id/cancel',async req=>db.tx(()=>{const t=requireRow(db.get('SELECT * FROM tournaments WHERE id=?',pathId(req.params)));organizer(db,current(req),t);if(!['DRAFT','OPEN','FULL'].includes(t.status))fail('A started tournament cannot be cancelled',409);db.run("UPDATE tournaments SET status='CANCELLED' WHERE id=?",t.id);audit(db,current(req),'TOURNAMENT_CANCEL',t.id,{});return {ok:true};}));
 app.delete('/api/tournaments/:id/players/:userId',async req=>db.tx(()=>{const p=z.object({id:entityId,userId:entityId}).parse(req.params);const t=requireRow(db.get('SELECT * FROM tournaments WHERE id=?',p.id));organizer(db,current(req),t);if(!['OPEN','FULL'].includes(t.status))fail('The player list is locked',409);db.run('DELETE FROM tournament_players WHERE tournament_id=? AND user_id=?',p.id,p.userId);db.run("UPDATE tournaments SET status='OPEN' WHERE id=?",p.id);audit(db,current(req),'TOURNAMENT_REMOVE_PLAYER',p.id,p);return {ok:true};}));
}
