import { useState } from 'react';
import { Link } from 'react-router-dom';
import { ShieldCheck, Search, Plus, Pencil } from 'lucide-react';
import { api, patch, post, useResource, datetime, type Row } from '../api';
import { useApp } from '../context';
import { PageTitle, Modal, FormError, Skeleton, ErrorView } from '../components/ui';
type Editor={title:string;path:string;method:string;value:unknown};
export default function Admin(){const {me,version,refresh,toast}=useApp();const {data,error,reload}=useResource<Row>('/admin/overview',version);const [tab,setTab]=useState('users'),[search,setSearch]=useState(''),[editor,setEditor]=useState<Editor|null>(null),[json,setJson]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 function edit(e:Editor){setEditor(e);setJson(JSON.stringify(e.value,null,2));setMessage('');}
 if(me.role!=='ADMIN')return <div className="empty"><ShieldCheck size={36}/><h2>Admin access required.</h2><Link className="btn" to="/">Back to your court</Link></div>;
 if(error)return <ErrorView message={error} retry={reload}/>;if(!data)return <Skeleton/>;
 const templates:Record<string,Editor>={packs:{title:'Create pack',path:'/admin/packs/'+crypto.randomUUID(),method:'PUT',value:{name:'New pack',price:200,active:true,probabilities:{COMMON:70,UNCOMMON:22,RARE:7,EPIC:1}}},stickers:{title:'Create collectible',path:'/admin/stickers/'+crypto.randomUUID(),method:'PUT',value:{name:'New sticker',description:'A new court collectible.',image_url:'/stickers/1.svg',rarity:'COMMON'}},achievements:{title:'Create achievement',path:'/admin/achievements',method:'POST',value:{name:'Regular on court',description:'Play 20 games',metric:'games',threshold:20,reward:50}},seasons:{title:'Create season',path:'/admin/seasons',method:'POST',value:{name:'Season 02',start_at:'2027-01-01T00:00:00.000Z',end_at:'2027-04-01T00:00:00.000Z',status:'UPCOMING'}},transactions:{title:'Adjust Pingpoints',path:'/admin/adjustments',method:'POST',value:{user_id:'alex',amount:100,description:'Community event reward',request_key:crypto.randomUUID()}}};
 return <><PageTitle eyebrow="KEEP THE COURT RUNNING" title="Club controls." description="Manage people, collectibles, and the game economy. Every change is audited." action={<Link className="btn primary" to="/tournaments">Manage tournaments</Link>}/><div className="tabs scroll-tabs">{['users','matches','transactions','stickers','packs','achievements','seasons','config','logs'].map(t=><button className={tab===t?'active':''} key={t} onClick={()=>setTab(t)}>{t==='config'?'Game rules':t}</button>)}</div><div className="filter-row"><label className="search-field"><Search size={18}/><input aria-label="Search admin records" placeholder="Search records…" value={search} onChange={e=>setSearch(e.target.value)}/></label>{templates[tab]&&<button className="btn primary" onClick={()=>edit(templates[tab])}><Plus size={18}/>{tab==='transactions'?'Adjust points':'Create'}</button>}{tab==='config'&&<button className="btn primary" onClick={()=>edit({title:'Edit game rules',path:'/admin/config',method:'PATCH',value:data.config})}><Pencil size={17}/>Edit rules</button>}</div>
 {tab==='config'?<div className="panel"><h2>Backend game configuration</h2><pre className="json-preview">{JSON.stringify(data.config,null,2)}</pre></div>:<div className="admin-records">{data[tab]?.filter((r:Row)=>JSON.stringify(r).toLowerCase().includes(search.toLowerCase())).map((r:Row,i:number)=><div className="admin-record" key={r.id||i}><div><strong>{r.display_name||r.name||r.action||r.description||r.title||r.id}</strong><small>{r.role?`${r.id} · ${r.role} · ${r.banned?'SUSPENDED':'ACTIVE'}`:r.created_at?datetime(r.created_at):r.id}</small></div>{tab==='users'?<button className="btn small" onClick={()=>edit({title:`Edit ${r.display_name}`,path:`/admin/users/${r.id}`,method:'PATCH',value:{role:r.role,banned:!!r.banned}})}>Manage</button>:tab==='packs'?<button className="btn small" onClick={()=>edit({title:`Edit ${r.name}`,path:`/admin/packs/${r.id}`,method:'PUT',value:{name:r.name,price:r.price,active:!!r.active,probabilities:JSON.parse(r.probabilities)}})}>Edit</button>:tab==='stickers'&&r.type==='COLLECTION'?<button className="btn small" onClick={()=>edit({title:`Edit ${r.name}`,path:`/admin/stickers/${r.id}`,method:'PUT',value:{name:r.name,description:r.description,image_url:r.image_url,rarity:r.rarity}})}>Edit</button>:null}<details><summary>Inspect record</summary><pre className="json-preview">{JSON.stringify(r,null,2)}</pre></details></div>)}</div>}<p className="footnote">Matches, transactions, and logs show the latest 100 records. User roles are checked on every backend request.</p>
 {editor&&<Modal title={editor.title} onClose={()=>!busy&&setEditor(null)}><form className="form-stack" onSubmit={async e=>{e.preventDefault();setBusy(true);setMessage('');try{const value=JSON.parse(json);await api(editor.path,{method:editor.method,body:JSON.stringify(value)});await refresh();setEditor(null);toast('Change saved and logged.');}catch(err){setMessage((err as Error).message);}finally{setBusy(false);}}}><p className="muted">Edit the fields below. Values are validated before saving. Monetary changes require a reason; use a new request key for a new adjustment.</p><label>Record fields (JSON)<textarea className="code-editor" rows={16} value={json} onChange={e=>setJson(e.target.value)} spellCheck={false}/></label><FormError message={message}/><button className="btn primary full" disabled={busy}>{busy?'Saving…':'Save changes'}</button></form></Modal>}</>;
}
