import { useRef } from 'react';
import { Link } from 'react-router-dom';
import { ArrowUpRight, Flame, Swords, Trophy, MapPin, Sparkles, Layers3 } from 'lucide-react';
import { useApp } from '../context';
import { useResource, number, date, type Row } from '../api';
import { League, SectionTitle, StickerCard, Avatar, Skeleton, ErrorView, Empty } from '../components/ui';
import { haptic } from '../telegram';
export function CourtArt(){return <svg className="court-art" viewBox="0 0 360 280" aria-hidden="true"><ellipse cx="183" cy="239" rx="120" ry="17" fill="#163f35" opacity=".13"/><g transform="rotate(-30 175 145)"><rect x="155" y="156" width="39" height="100" rx="19" fill="#f8c454"/><ellipse cx="175" cy="109" rx="80" ry="88" fill="#284d42"/><ellipse cx="170" cy="102" rx="77" ry="85" fill="#ee7890"/><ellipse cx="164" cy="96" rx="59" ry="66" fill="none" stroke="#ffb2c1" strokeWidth="2" strokeDasharray="2 7"/><text x="171" y="103" textAnchor="middle" fontSize="22" fontWeight="800" fill="#fffde9">пинг</text><text x="171" y="128" textAnchor="middle" fontSize="18" fontWeight="800" fill="#fffde9">таблет</text></g><path d="M274 206c36-35 10-73-21-51" fill="none" stroke="#fffde9" strokeWidth="3" strokeDasharray="4 8"/><circle cx="72" cy="190" r="8" fill="#fffde9"/><path d="m284 52 4-14 5 14 14 4-14 5-5 14-4-14-14-5z" fill="#ffcb58"/></svg>;}
function PlayfulBall(){const ref=useRef<HTMLButtonElement>(null);return <button ref={ref} className="playful-ball" aria-label="Подбросить мяч" onClick={()=>{haptic('medium');if(!matchMedia('(prefers-reduced-motion: reduce)').matches&&document.documentElement.dataset.motion!=='off')ref.current?.animate([{transform:'translateY(0) scale(1.18,.8)'},{transform:'translateY(-55px) scale(.9,1.1)',offset:.38},{transform:'translateY(0) scale(1.12,.86)',offset:.75},{transform:'translateY(0) scale(1)'}],{duration:680,easing:'cubic-bezier(.3,.7,.3,1)'});}}><span/><span className="ball-shine"/></button>;}
export default function Home(){
 const {me,version}=useApp();const tournaments=useResource<Row[]>('/tournaments',version),matches=useResource<Row[]>('/matches?limit=4',version),stickers=useResource<Row[]>('/me/stickers',version);
 const upcoming=tournaments.data?.find(t=>t.status==='OPEN');const picks=stickers.data?.filter(s=>s.quantity>0&&s.type==='COLLECTION').slice(0,4);
 return <><div className="home-greeting"><div><span className="eyebrow">рады видеть тебя</span><h1>Привет, {me.display_name.split(' ')[0]}<span className="greeting-star">✳</span></h1><p>Хороший день для ещё одной партии.</p></div><Link to="/profile"><Avatar user={me} size="large"/></Link></div>
 <section className="hero"><div className="hero-content"><span className="hero-label">сезон 01 · первая подача</span><h2>всё начинается<br/>с <em>подачи.</em></h2><p>Свои люди, новые соперники<br/>и маленькие большие победы.</p><Link to="/play" className="btn primary">Сыграем? <ArrowUpRight size={21}/></Link></div><div className="hero-playground"><CourtArt/><PlayfulBall/><span className="ball-hint">нажми на мяч ↗</span></div><span className="hero-bottom">играем. знакомимся. собираем.</span></section>
 <section className="home-stats"><Link to="/statistics" className="rating-card"><div className="card-top"><span>твой рейтинг</span><ArrowUpRight size={18}/></div><div className="rating-number">{number(me.rating)} <League value={me.league}/></div><div className="rating-progress"><span style={{width:`${Math.min(100,Math.max(0,(me.rating%200)/2))}%`}}/></div><small>{me.rating>=1800?'Высшая лига. Продолжай в том же духе.':`До следующей лиги: ${200-me.rating%200} очков`}</small></Link><Link to="/statistics" className="mini-stat"><span className="stat-icon"><Flame size={23}/></span><div><strong>{me.streak}</strong><span>побед подряд</span></div></Link><Link to="/collection" className="mini-stat"><span className="stat-icon"><Layers3 size={23}/></span><div><strong>{me.collection}<small> / 100</small></strong><span>стикеров собрано</span></div></Link></section>
 <div className="home-columns"><div><SectionTitle title="Встречаемся за столом" to="/tournaments"/>{tournaments.error?<ErrorView message={tournaments.error} retry={tournaments.reload}/>:!tournaments.data?<Skeleton/>:upcoming?<Link to={`/tournaments/${upcoming.id}`} className="featured-tournament"><div className="tournament-visual"><div className="trophy-orbit"><Trophy size={54} strokeWidth={1.5}/></div><span className="badge">регистрация открыта</span></div><div className="tournament-info"><span className="eyebrow">на выбывание</span><h3>{upcoming.title}</h3><p><MapPin size={15}/>{upcoming.location}</p><div className="tournament-meta"><span>{date(upcoming.start_at)}</span><span>{upcoming.player_count}/{upcoming.max_players} игроков</span></div></div></Link>:<Empty title="Турниры скоро появятся" text="А пока найди соперника и сыграй дружеский матч." action={<Link className="btn" to="/play">Найти игрока</Link>}/>}
 <SectionTitle title="Твои маленькие трофеи" to="/collection"/>{stickers.error?<ErrorView message={stickers.error} retry={stickers.reload}/>:!stickers.data?<Skeleton/>:picks?.length?<div className="sticker-preview">{picks.map(s=><Link to="/collection" key={s.id}><StickerCard sticker={s}/></Link>)}</div>:<Empty title="Первый стикер уже ждёт" action={<Link className="btn" to="/shop">Выбрать набор</Link>}/>}</div>
 <div><SectionTitle title="Что сегодня?"/><div className="quick-actions"><Link to="/play"><span className="action-icon"><Swords size={24}/></span><span><strong>Найти соперника</strong><small>Одна партия — уже хороший план.</small></span><ArrowUpRight size={21}/></Link><Link to="/shop"><span className="action-icon"><Sparkles size={24}/></span><span><strong>Открыть что-то новое</strong><small>Три стикера. Твой маленький сюрприз.</small></span><ArrowUpRight size={21}/></Link></div><SectionTitle title="Последние партии" to="/play" label="История"/><div className="activity-list">{matches.error?<ErrorView message={matches.error} retry={matches.reload}/>:!matches.data?<Skeleton/>:!matches.data.length?<Empty title="Твоя история начинается здесь" text="Запиши результат первой партии."/>:matches.data.map(m=>{const won=m.winner===me.id,delta=m.player_a===me.id?m.rating_change_a:m.rating_change_b;return <Link to="/play" className="activity-row" key={m.id}><span className={`result-mark ${won?'win':'loss'}`}>{m.status==='PENDING'?'…':won?'↗':'↘'}</span><div><strong>{m.player_a===me.id?m.name_b:m.name_a}</strong><small>{m.score_a} : {m.score_b} · {date(m.created_at)}</small></div><span className={won?'positive':'muted'}>{m.status==='PENDING'?'Ждём':m.status!=='CONFIRMED'?'Отменён':`${delta>=0?'+':''}${delta}`}</span></Link>;})}</div></div></div></>;
}
