import { Link } from 'react-router-dom';
import { ArrowUpRight, ArrowRight, Flame, Swords, Trophy, MapPin, CalendarDays, Sparkles, Layers3, Zap } from 'lucide-react';
import { useApp } from '../context';
import { useResource, number, date, type Row } from '../api';
import { League, SectionTitle, StickerCard, Avatar } from '../components/ui';
export function CourtArt(){return <svg className="court-art" viewBox="0 0 540 350" aria-hidden="true"><defs><linearGradient id="paddle" x2="1" y2="1"><stop stopColor="#e3ff8a"/><stop offset="1" stopColor="#91bd29"/></linearGradient><pattern id="rubber" width="7" height="7" patternUnits="userSpaceOnUse"><circle cx="2" cy="2" r="1" fill="#284212" opacity=".24"/></pattern><linearGradient id="table" x2="0" y2="1"><stop stopColor="#3b4936"/><stop offset="1" stopColor="#1b241a"/></linearGradient></defs><ellipse cx="320" cy="289" rx="174" ry="27" fill="#080d06" opacity=".6"/><path d="m152 240 218-125 206 121-218 120z" fill="url(#table)" stroke="#66735b" strokeWidth="2"/><path d="m174 242 196-114 183 107-196 108zM266 188l180 107" fill="none" stroke="#b4c5a7" strokeWidth="2" opacity=".4"/><g transform="rotate(34 320 166)"><rect x="302" y="198" width="43" height="108" rx="11" fill="#ad7853" stroke="#d4a274" strokeWidth="3"/><path d="M313 228v61m12-61v61" stroke="#795330" strokeWidth="3"/><ellipse cx="322" cy="132" rx="88" ry="104" fill="#252b22" stroke="#171d13" strokeWidth="5"/><ellipse cx="318" cy="126" rx="88" ry="104" fill="url(#paddle)" stroke="#e6fbbb" strokeWidth="3"/><ellipse cx="318" cy="126" rx="84" ry="100" fill="url(#rubber)"/><text x="319" y="139" fontSize="29" fontFamily="Arial,sans-serif" fontWeight="900" textAnchor="middle" fill="#294114">PING.</text></g><circle cx="192" cy="130" r="29" fill="#f9f9e9"/><circle cx="185" cy="123" r="10" fill="#fff" opacity=".7"/><path d="M171 154c-38 25-47 61-22 84" fill="none" stroke="#c7f54a" strokeWidth="2" strokeDasharray="5 7"/><path d="m436 80 8-20m-1 28 20-9" stroke="#c7f54a" strokeWidth="3" strokeLinecap="round"/></svg>;}
export default function Home(){const {me,version}=useApp();const tournaments=useResource<Row[]>('/tournaments',version),matches=useResource<Row[]>('/matches?limit=4',version),stickers=useResource<Row[]>('/me/stickers',version);const upcoming=tournaments.data?.find(t=>t.status==='OPEN');const picks=stickers.data?.filter(s=>s.quantity>0&&s.type==='COLLECTION').sort((a,b)=>b.id.localeCompare(a.id)).slice(0,4);
 return <><div className="home-greeting"><div><span className="eyebrow">GOOD TO SEE YOU BACK</span><h1>Let’s rally, {me.display_name.split(' ')[0]}<span className="lime">.</span></h1><p>Another day. Another chance to level up.</p></div><span className="season-label"><span className="live-dot"/> FIRST SERVE · SEASON 01</span></div>
 <section className="hero"><div className="hero-content"><span className="hero-label"><span/> YOUR GAME. LEVELED UP.</span><h2>More than<br/>a <em>game.</em></h2><p>Play your people. Climb the ranks.<br/>Build a collection that’s all you.</p><Link to="/play" className="btn primary">Let’s play <ArrowUpRight size={21}/></Link></div><CourtArt/><span className="hero-coordinate">52.3676° N / 4.9041° E</span><span className="hero-bottom">EVERY RALLY COUNTS.</span></section>
 <section className="home-stats"><Link to="/statistics" className="rating-card"><div className="card-top"><span>YOUR RATING</span><ArrowUpRight size={17}/></div><div className="rating-number">{number(me.rating)} <League value={me.league}/></div><div className="rating-progress"><span style={{width:`${Math.min(100,Math.max(0,(me.rating%200)/2))}%`}}/></div><small>{me.rating>=1800?'Top league. Keep pushing.':`${200-me.rating%200} points to your next league`}</small></Link><Link to="/statistics" className="mini-stat"><span className="stat-icon fire"><Flame size={23}/></span><div><strong>{me.streak}<small> WINS</small></strong><span>Current streak</span></div><span className="tiny-tag">ON FIRE</span></Link><Link to="/collection" className="mini-stat"><span className="stat-icon purple"><Layers3 size={23}/></span><div><strong>{me.collection}<small> / 100</small></strong><span>Stickers collected</span></div><ArrowUpRight size={19}/></Link></section>
 <div className="home-columns"><div><SectionTitle title="Up next on your court" to="/tournaments"/>{upcoming?<Link to={`/tournaments/${upcoming.id}`} className="featured-tournament"><div className="tournament-visual"><div className="trophy-orbit"><Trophy size={54} strokeWidth={1.5}/></div><span className="badge">REGISTRATION OPEN</span><span className="visual-text">GOOD GAMES.<br/>GREAT PEOPLE.</span></div><div className="tournament-info"><div className="card-top"><span className="eyebrow">SINGLE ELIMINATION</span><ArrowUpRight size={19}/></div><h3>{upcoming.title}</h3><p><MapPin size={15}/>{upcoming.location}</p><div className="tournament-meta"><span><CalendarDays size={15}/>{date(upcoming.start_at)}</span><span>{upcoming.player_count}/{upcoming.max_players} players</span></div><div className="tiny-progress"><span style={{width:`${upcoming.player_count/upcoming.max_players*100}%`}}/></div></div></Link>:<div className="panel"><p>No upcoming tournaments yet.</p><Link to="/tournaments">Explore tournaments →</Link></div>}
 <SectionTitle title="Fresh in your collection" to="/collection"/><div className="sticker-preview">{picks?.map(s=><Link to="/collection" key={s.id}><StickerCard sticker={s}/></Link>)}</div></div><div><SectionTitle title="Make your next move"/><div className="quick-actions"><Link to="/play"><span className="action-icon lime-bg"><Swords size={23}/></span><span><strong>Find your next rival</strong><small>Good competition starts here.</small></span><ArrowUpRight size={21}/></Link><Link to="/shop"><span className="action-icon lilac-bg"><Sparkles size={23}/></span><span><strong>A little pack magic</strong><small>Three stickers. Endless possibilities.</small></span><ArrowUpRight size={21}/></Link></div><SectionTitle title="Your last rallies" to="/play" label="History"/><div className="activity-list">{matches.data?.map(m=>{const won=m.winner===me.id;const delta=m.player_a===me.id?m.rating_change_a:m.rating_change_b;return <Link to={`/players/${m.player_a===me.id?m.player_b:m.player_a}`} className="activity-row" key={m.id}><span className={`result-mark ${won?'win':'loss'}`}>{m.status==='PENDING'?'…':won?'W':'L'}</span><div><strong>vs {m.player_a===me.id?m.name_b:m.name_a}</strong><small>{m.score_a} – {m.score_b} <span>·</span> {date(m.created_at)}</small></div><span className={won?'positive':'muted'}>{m.status==='PENDING'?'Pending':`${delta>=0?'+':''}${delta}`}<small> ELO</small></span></Link>;})}</div><Link className="season-card" to="/leaderboard"><Zap size={22}/><span>There’s a new level<br/>with your name on it.</span><ArrowRight size={21}/></Link></div></div></>;
}
