import { useState, useCallback } from 'react';
import { Link } from 'react-router-dom';
import { Search, Plus, Check, X, Swords } from 'lucide-react';
import { api, post, useResource, date, type Row } from '../api';
import { useApp } from '../context';
import { Avatar, PageTitle, Modal, FormError, Skeleton, ErrorView, Empty, League } from '../components/ui';
import { useTelegramAction } from '../telegram';
export default function Play(){const {me,refresh,toast,version}=useApp();const [search,setSearch]=useState(''),[debounced,setDebounced]=useState('');const players=useResource<Row[]>(`/players?search=${encodeURIComponent(debounced)}`);const matches=useResource<Row[]>('/matches',version);const [opponent,setOpponent]=useState<Row|null>(null),[a,setA]=useState('11'),[b,setB]=useState('8'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[tab,setTab]=useState('players'),[requestKey,setRequestKey]=useState('');
 async function submit(){if(!opponent||busy)return;setBusy(true);setError('');try{await post('/matches',{opponent_id:opponent.id,score_a:Number(a),score_b:Number(b),request_key:requestKey});setOpponent(null);await refresh();setTab('matches');toast('Result sent. Your opponent can now confirm it.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const telegramSubmit=useCallback(()=>{void submit();},[opponent,a,b,busy,requestKey]);useTelegramAction('SEND RESULT',telegramSubmit,!!opponent);
 async function action(mid:string,kind:string){setBusy(true);try{await post(`/matches/${mid}/${kind}`);await refresh();toast(kind==='confirm'?'Match confirmed. Rating and rewards updated.':'Result updated.');}catch(e){toast((e as Error).message);}finally{setBusy(false);}}
 const pending=matches.data?.filter(m=>m.status==='PENDING')||[];
 return <><PageTitle eyebrow="MEET AT THE TABLE" title="Ready to rally?" description="Find a player, play a game, make it count."/><div className="info-banner"><Swords size={23}/><div><strong>Play in person. Level up here.</strong><span>Record one completed game, first to 11 and win by 2. Your opponent confirms the result.</span></div></div><div className="tabs"><button className={tab==='players'?'active':''} onClick={()=>setTab('players')}>Find players</button><button className={tab==='matches'?'active':''} onClick={()=>setTab('matches')}>My matches {pending.length>0&&<span className="count">{pending.length}</span>}</button></div>
 {tab==='players'?<><form className="search-field" onSubmit={e=>{e.preventDefault();setDebounced(search);}}><Search size={19}/><input aria-label="Search players" placeholder="Find a name or @username…" value={search} onChange={e=>setSearch(e.target.value)}/><button type="submit" className="btn small">Search</button></form>{players.error?<ErrorView message={players.error} retry={players.reload}/>:!players.data?<Skeleton/>:<div className="players-grid">{players.data.filter(p=>p.id!==me.id).map(p=><div className="player-card" key={p.id}><Link to={`/players/${p.id}`} className="player-card-main"><Avatar user={p} size="large"/><div><h3>{p.display_name}</h3><p>@{p.username}</p><League value={p.league}/></div><strong>{p.rating}</strong></Link><div className="player-card-bottom"><span>{p.city||'The global court'}</span><button className="btn small" onClick={()=>{setOpponent(p);setRequestKey(crypto.randomUUID());setError('');}}>Record match <Plus size={15}/></button></div></div>)}{players.data.length===0&&<Empty title="No players found" text="Try a different name or username."/>}</div>}</>:matches.error?<ErrorView message={matches.error} retry={matches.reload}/>:!matches.data?<Skeleton/>:<div className="match-list">{matches.data.map(m=><div className="match-card" key={m.id}><div><span className={`badge status-${m.status.toLowerCase()}`}>{m.status}</span><small className="muted">{date(m.created_at)}</small></div><div className="match-score"><Link to={`/players/${m.player_a}`}>{m.name_a}</Link><strong>{m.score_a} <span>:</span> {m.score_b}</strong><Link to={`/players/${m.player_b}`}>{m.name_b}</Link></div>{m.status==='PENDING'?<div className="match-actions">{m.player_b===me.id?<><span>Is this result correct?</span><button className="btn primary small" disabled={busy} onClick={()=>action(m.id,'confirm')}><Check size={15}/>Confirm</button><button className="btn small" disabled={busy} onClick={()=>action(m.id,'reject')}><X size={15}/>Reject</button></>:<><span>Waiting for your opponent</span><button className="btn small" disabled={busy} onClick={()=>action(m.id,'cancel')}>Cancel result</button></>}</div>:m.status==='CONFIRMED'&&<div className="match-actions"><span>{m.winner===me.id?'Victory. Nicely played.':'Every rally makes you better.'}</span><strong className={m.winner===me.id?'positive':'muted'}>{(m.player_a===me.id?m.rating_change_a:m.rating_change_b)>=0?'+':''}{m.player_a===me.id?m.rating_change_a:m.rating_change_b} ELO</strong></div>}</div>)}{!matches.data.length&&<Empty title="Your first match is waiting." action={<button className="btn primary" onClick={()=>setTab('players')}>Find a player</button>}/>}</div>}
 {opponent&&<Modal title="Record your match" onClose={()=>!busy&&setOpponent(null)}><form onSubmit={e=>{e.preventDefault();void submit();}}><p className="muted">Your opponent will confirm this score before it affects your rating.</p><div className="score-inputs"><label>{me.display_name.split(' ')[0]}<input aria-label="Your score" type="number" min="0" max="99" required value={a} onChange={e=>setA(e.target.value)}/></label><span>:</span><label>{opponent.display_name.split(' ')[0]}<input aria-label="Opponent score" type="number" min="0" max="99" required value={b} onChange={e=>setB(e.target.value)}/></label></div><FormError message={error}/><button className="btn primary full" disabled={busy}>{busy?'Sending…':'Send result'}</button></form></Modal>}</>;
}
