import { useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { MapPin, Pencil, Layers3, BarChart3, Award, Settings2, ArrowUpRight, Upload } from 'lucide-react';
import { patch, useResource, type Row } from '../api';
import { useApp } from '../context';
import { Avatar, PageTitle, League, Stat, Modal, FormError, Skeleton, ErrorView } from '../components/ui';
export default function Profile(){const {id}=useParams();const {me,version,refresh,toast}=useApp();const own=!id||id===me.id;const {data,error,reload}=useResource<Row>(`/players/${id||me.id}`,version);const [editing,setEditing]=useState(false),[form,setForm]=useState({display_name:'',city:'',bio:'',profile_photo:''}),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 function edit(){setForm({display_name:me.display_name,city:me.city,bio:me.bio,profile_photo:me.profile_photo||''});setMessage('');setEditing(true);}
 async function photo(file?:File){if(!file)return;if(!['image/png','image/jpeg','image/webp'].includes(file.type)){setMessage('Choose a PNG, JPEG, or WebP photo.');return;}if(file.size>8_000_000){setMessage('Choose a photo smaller than 8 MB.');return;}const img=new Image(),url=URL.createObjectURL(file);img.onload=()=>{const canvas=document.createElement('canvas');canvas.width=384;canvas.height=384;const side=Math.min(img.width,img.height);canvas.getContext('2d')!.drawImage(img,(img.width-side)/2,(img.height-side)/2,side,side,0,0,384,384);setForm(f=>({...f,profile_photo:canvas.toDataURL('image/jpeg',0.82)}));setMessage('');URL.revokeObjectURL(url);};img.onerror=()=>{setMessage('Could not read that image.');URL.revokeObjectURL(url);};img.src=url;}
 if(error)return <ErrorView message={error} retry={reload}/>;if(!data)return <Skeleton/>;const p=own?me:data;
 return <><PageTitle eyebrow={own?'YOUR PLAYER CARD':'MEET YOUR COMPETITION'} title={own?'Made for the game.':p.display_name} action={own?<button className="btn" onClick={edit}><Pencil size={16}/>Edit profile</button>:<Link className="btn primary" to="/play">Record a match <ArrowUpRight size={18}/></Link>}/><section className="profile-hero"><div className="profile-identity"><Avatar user={p} size="huge"/><div><League value={p.league}/><h2>{p.display_name}</h2><p>@{p.username}</p><span><MapPin size={15}/>{p.city||'The global court'}</span></div></div><div className="profile-rating"><span>ELO RATING</span><strong>{p.rating}</strong><small>PEAK {p.highest_rating}</small></div><p className="profile-bio">{p.bio||'A new story at the table.'}</p></section><div className="stats-grid"><Stat label="Games played" value={p.games}/><Stat label="Wins" value={p.wins}/><Stat label="Losses" value={p.losses}/><Stat label="Win rate" value={`${p.win_rate}%`}/><Stat label="Current streak" value={p.streak}/><Stat label="Longest streak" value={p.longest_streak}/><Stat label="Tournament wins" value={p.tournament_wins}/><Stat label="Podiums" value={p.podiums}/></div>{own?<div className="profile-links">{[['/collection','Your sticker collection',`${p.collection} / 100 discovered`,Layers3],['/statistics','Your numbers, your story','A closer look at your game',BarChart3],['/achievements','The trophy shelf','Celebrate every milestone',Award]].map(([to,title,text,Icon]:any)=><Link to={to} key={to}><Icon size={27}/><div><strong>{title}</strong><span>{text}</span></div><ArrowUpRight size={20}/></Link>)}{me.role==='ADMIN'&&<Link to="/admin"><Settings2 size={27}/><strong>Admin controls</strong><ArrowUpRight size={20}/></Link>}</div>:<section className="panel"><PageTitle eyebrow="HEAD TO HEAD" title={`${me.display_name.split(' ')[0]} vs ${p.display_name.split(' ')[0]}`}/><div className="stats-grid three"><Stat label="Games together" value={data.head_to_head.games}/><Stat label="Your wins" value={data.head_to_head.wins}/><Stat label="Your losses" value={data.head_to_head.losses}/></div>{data.head_to_head.matches.map((m:Row)=><div className="ledger-row" key={m.id}><span>{m.name_a} vs {m.name_b}</span><strong>{m.score_a} : {m.score_b}</strong></div>)}<Link className="btn" to={`/statistics/${p.id}`}>View statistics <BarChart3 size={17}/></Link></section>}
 {editing&&<Modal title="Make it yours." onClose={()=>!busy&&setEditing(false)}><form className="form-stack" onSubmit={async e=>{e.preventDefault();setBusy(true);setMessage('');try{await patch('/me/profile',form);await refresh();setEditing(false);toast('Profile updated. Looking good.');}catch(err){setMessage((err as Error).message);}finally{setBusy(false);}}}><div className="photo-picker"><Avatar user={{...me,profile_photo:form.profile_photo}} size="large"/><label className="btn"><Upload size={16}/>Choose photo<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>photo(e.target.files?.[0])}/></label>{form.profile_photo&&<button type="button" className="text-button" onClick={()=>setForm({...form,profile_photo:''})}>Remove</button>}</div><label>Display name<input required maxLength={50} value={form.display_name} onChange={e=>setForm({...form,display_name:e.target.value})}/></label><label>City<input maxLength={80} value={form.city} onChange={e=>setForm({...form,city:e.target.value})}/></label><label>Bio<textarea maxLength={300} rows={3} value={form.bio} onChange={e=>setForm({...form,bio:e.target.value})}/></label><p className="muted">Telegram ID: {me.telegram_id}</p><FormError message={message}/><button className="btn primary full" disabled={busy}>{busy?'Saving…':'Save profile'}</button></form></Modal>}</>;
}
