import { useState, useCallback } from 'react';
import { Link } from 'react-router-dom';
import { Sparkles, ArrowUpRight, Coins, Check } from 'lucide-react';
import { post, useResource, number, type Row } from '../api';
import { useApp } from '../context';
import { PageTitle, Modal, StickerCard, FormError, Skeleton, ErrorView } from '../components/ui';
import { useTelegramAction } from '../telegram';
export default function Shop(){const {me,refresh,toast}=useApp();const {data,error,reload}=useResource<Row[]>('/packs');const [pack,setPack]=useState<Row|null>(null),[rewards,setRewards]=useState<Row[]|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[requestKey,setRequestKey]=useState('');
 async function buy(){if(!pack||busy)return;setBusy(true);setMessage('');try{const result=await post(`/packs/${pack.id}/open`,{request_key:requestKey});setRewards(result.rewards);setPack(null);await refresh();toast('Три новых стикера уже в твоей коллекции!');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 const buyCallback=useCallback(()=>{void buy();},[pack,busy,requestKey]);useTelegramAction(pack?`ОТКРЫТЬ ЗА ${pack.price} ПП`:'ОТКРЫТЬ НАБОР',buyCallback,!!pack);
 return <><PageTitle eyebrow="немного магии" title="Что внутри?" description="Три стикера в каждом наборе. Найди свой любимый." action={<Link to="/wallet" className="balance-display"><Coins size={24}/><span>{number(me.pingpoints)}<small>твои пингпоинты</small></span></Link>}/>{error?<ErrorView message={error} retry={reload}/>:!data?<Skeleton/>:<div className="pack-grid">{data.map((p,i)=><article className={`pack-card pack-${i}`} key={p.id}><span className="eyebrow">{i===0?'маленькая радость':i===1?'ещё больше сюрпризов':'за редкими находками'}</span><div className="pack-art"><div className="pack-wrapper"><div className="pack-seal"/><span className="pack-brand">PING.</span><Sparkles size={67} strokeWidth={1}/><strong>{p.name.toUpperCase()}</strong><span>3 стикера в коллекцию</span><div className="pack-seal bottom"/></div><span className="pack-spark s1">✦</span><span className="pack-spark s2">✧</span></div><h2>набор «{p.name}»</h2><p>{i===0?'Маленький набор. Большие возможности.':i===1?'Больше шансов на редкую находку.':'Самые редкие стикеры ждут тебя.'}</p><button className="btn primary full" disabled={me.pingpoints<p.price} onClick={()=>{setPack(p);setRequestKey(crypto.randomUUID());setMessage('');}}><Coins size={17}/>{number(p.price)} ПП <ArrowUpRight size={17}/></button>{me.pingpoints<p.price&&<small className="muted">Earn {number(p.price-me.pingpoints)} more ПП to open</small>}<details><summary>Шансы выпадения</summary><div className="odds">{Object.entries(p.probabilities).map(([r,w])=><div key={r}><span className={`rarity-${r.toLowerCase()}`}>{r}</span><strong>{String(w)}%</strong></div>)}</div></details></article>)}</div>}<div className="shop-note"><Check size={22}/><div><strong>Коллекция — для радости. Игра — честная.</strong><p>Стикеры не влияют на рейтинг. Каждый розыгрыш независим: в наборе могут быть повторы.</p></div></div>
 {pack&&<Modal title={`Открыть набор «${pack.name}»?`} onClose={()=>!busy&&setPack(null)}><p>Ты получишь 3 случайных стикера за <strong>{number(pack.price)} ПП</strong>.</p><p className="muted">После покупки останется: {number(me.pingpoints-pack.price)} ПП</p><FormError message={message}/><button className="btn primary full" onClick={buy} disabled={busy}>{busy?'Открываем набор…':`Подтвердить · ${number(pack.price)} ПП`}</button></Modal>}
 {rewards&&<Modal title="Твои новые находки!" onClose={()=>setRewards(null)}><p className="muted">Только из набора. Уже в твоей коллекции.</p><div className="reveal-cards">{rewards.map((s,i)=><div key={i} style={{animationDelay:`${i*180}ms`}}><StickerCard sticker={s}/></div>)}</div><Link className="btn primary full" to="/collection">В коллекцию <ArrowUpRight size={18}/></Link><button className="btn full" onClick={()=>setRewards(null)}>Ещё немного магии</button></Modal>}</>;
}
