import { useState, useCallback } from 'react';
import { Link } from 'react-router-dom';
import { Sparkles, ArrowUpRight, Coins, Check } from 'lucide-react';
import { post, useResource, number, type Row } from '../api';
import { useApp } from '../context';
import { PageTitle, Modal, StickerCard, FormError, Skeleton, ErrorView } from '../components/ui';
import { useTelegramAction } from '../telegram';
export default function Shop(){const {me,refresh,toast}=useApp();const {data,error,reload}=useResource<Row[]>('/packs');const [pack,setPack]=useState<Row|null>(null),[rewards,setRewards]=useState<Row[]|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[requestKey,setRequestKey]=useState('');
 async function buy(){if(!pack||busy)return;setBusy(true);setMessage('');try{const result=await post(`/packs/${pack.id}/open`,{request_key:requestKey});setRewards(result.rewards);setPack(null);await refresh();toast('Three new arrivals. Make room in your collection.');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 const buyCallback=useCallback(()=>{void buy();},[pack,busy,requestKey]);useTelegramAction(pack?`OPEN FOR ${pack.price} PP`:'OPEN PACK',buyCallback,!!pack);
 return <><PageTitle eyebrow="A LITTLE PACK MAGIC" title="Unwrap the unexpected." description="Three stickers in every pack. What’s your next find?" action={<Link to="/wallet" className="balance-display"><Coins size={24}/><span>{number(me.pingpoints)}<small>YOUR PINGPOINTS</small></span></Link>}/>{error?<ErrorView message={error} retry={reload}/>:!data?<Skeleton/>:<div className="pack-grid">{data.map((p,i)=><article className={`pack-card pack-${i}`} key={p.id}><span className="eyebrow">{i===0?'THE EVERYDAY FIND':i===1?'A LITTLE EXTRA SPIN':'GO FOR THE EXTRAORDINARY'}</span><div className="pack-art"><div className="pack-wrapper"><div className="pack-seal"/><span className="pack-brand">PING.</span><Sparkles size={67} strokeWidth={1}/><strong>{p.name.toUpperCase()}</strong><span>3 COLLECTIBLE STICKERS</span><div className="pack-seal bottom"/></div><span className="pack-spark s1">✦</span><span className="pack-spark s2">✧</span></div><h2>{p.name} pack</h2><p>{i===0?'Small pack. Big possibilities.':i===1?'Better odds. Brighter discoveries.':'The rarest finds are out there.'}</p><button className="btn primary full" disabled={me.pingpoints<p.price} onClick={()=>{setPack(p);setRequestKey(crypto.randomUUID());setMessage('');}}><Coins size={17}/>{number(p.price)} PP <ArrowUpRight size={17}/></button>{me.pingpoints<p.price&&<small className="muted">Earn {number(p.price-me.pingpoints)} more PP to open</small>}<details><summary>See rarity odds</summary><div className="odds">{Object.entries(p.probabilities).map(([r,w])=><div key={r}><span className={`rarity-${r.toLowerCase()}`}>{r}</span><strong>{String(w)}%</strong></div>)}</div></details></article>)}</div>}<div className="shop-note"><Check size={22}/><div><strong>All style. Always fair play.</strong><p>Packs contain collectibles. Your rating comes from the game. Each draw is independent, and duplicates are part of collecting.</p></div></div>
 {pack&&<Modal title={`Open a ${pack.name} pack?`} onClose={()=>!busy&&setPack(null)}><p>You’ll receive 3 random stickers for <strong>{number(pack.price)} PP</strong>.</p><p className="muted">Balance after purchase: {number(me.pingpoints-pack.price)} PP</p><FormError message={message}/><button className="btn primary full" onClick={buy} disabled={busy}>{busy?'Opening your pack…':`Confirm · ${number(pack.price)} PP`}</button></Modal>}
 {rewards&&<Modal title="Meet your new finds." onClose={()=>setRewards(null)}><p className="muted">Fresh out of the pack. Already in your collection.</p><div className="reveal-cards">{rewards.map((s,i)=><div key={i} style={{animationDelay:`${i*180}ms`}}><StickerCard sticker={s}/></div>)}</div><Link className="btn primary full" to="/collection">View collection <ArrowUpRight size={18}/></Link><button className="btn full" onClick={()=>setRewards(null)}>Keep exploring</button></Modal>}</>;
}
